version: '3'
services:
  app:
    build: .
    image: rex/java-web-app:dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      #- LOGGING_FILE=/tmp/logs/ferryman.log
    volumes:
      - .:/tmp/src
